### ISSUE TITLE
parse stats that are part of a table. (for shaped-import-statblock)

### ISSUE THREAD

**Issue by harvimt** [symposion/roll20-shaped-scripts#239]
This is necessary to support statblocks produced by /u/itsadndmonsternow (without modification)

Example: https://www.reddit.com/r/birdswitharms/comments/53qzgy/steampunkheinz_2017_by_florian_stitz_xpost/d7xtyhw?context=3

**Comment by symposion** [comment]
Hi, 

This is out of scope for this project right now. The parser was written with the intention of supporting specifically the Monster Manual layout. 

That said, this statblock imported ok for me once I'd edited the speed and senses values to use "ft." rather than "'". I'd suggest that you paste via plain text first, and then into Roll20 - I think you'll find it works better.
