### ISSUE TITLE
parse single quote as a tick mark meaning foot. (for import-monster-statblock)

### ISSUE THREAD

**Issue by harvimt** [symposion/roll20-shaped-scripts#240]
this one is more minor, but seems easier to implement.
support tick marks for "foot"

like:
senses: Darkvision 60'
instead of
senses: Darkvision 60ft

not sure exactly how to do this, maybe add some stuff to sanitize, like

    .replace(/\b(\d+)'\b/g, '$1 ft')

again also necessary for supporting stat blocks from /u/itsadndmonsternow

**Comment by symposion** [comment]
Hi,

I don't really want to get into this - it's a slippery slope into supporting all sorts of variant formats. I know this particular change is a minor one, but if I start down this route I don't know where it ends. There's a clear standard available for monster statblocks, which is the WotC MM layout and this is what the script supports. 

Also, the sanitise stuff is exceedingly fragile already - we do it to try and reduce the pain of people coming from OCRed copies of things, but every time I introduce a new rule it breaks things in unforeseen ways, not least because there are multiple stages of transformations that it goes through. Quote marks in particular are one of the unwanted artefacts introduced by some OCR software, so we have to be super careful how we make the change.

Given that you have (I assume) a known format  that you are working with here, it makes more sense to me that you create a scraped/converter specifically designed to take this known, predictable format and translate it to something that is acceptable to the parser before you paste it in to Roll20, rather than me adding transformations to a generic script which doesn't know where its input is coming from. Alternatively, you could try persuading your fellow Redditors that they should follow the clear standards set out by WotC in formatting their 5e statblocks rather than introducing yet another variation into the world ;-)
