### ISSUE TITLE
Spell slots don't auto-decrement

### ISSUE THREAD

**Issue by Netoen** [symposion/roll20-shaped-scripts#258]
sheet version 7.0.7; companion script v4.9.0
I've tried so far: existing characters' spells; Adding new spells to those characters; Creating new empty character and adding spells for it.
I must mention that other features do automatically work for the most part.

**Comment by symposion** [comment]
This is a duplicate of #16 - this feature is not yet implemented because there were a lot of problems with getting it to work correctly. I think the sheet is now in a position where it may be possible to do this correctly so hopefully when I get a bit more time in a few weeks I can get this sorted out.
