### ISSUE TITLE
Traits should allow for parenthesis

### ISSUE THREAD

**Issue by mlenser** [symposion/roll20-shaped-scripts#262]
Traits currently do not allow parenthesis. This is problematic for cases like "Innate Spellcasting (Psionics)".

Parenthesis should be allowed.

**Comment by mlenser** [comment]
Fix for 8.0.0 please

**Comment by symposion** [comment]
Ok cool this should be easy enough I think

**Comment by mlenser** [comment]
This follows the same logic as https://github.com/symposion/roll20-shaped-scripts/issues/261

The things that go in parenthesis are things like "(Vampire Form Only)" which by your argument in the other thread would be in an annotations field, not a name field.
I'm not sure what the best option here is...

**Comment by symposion** [comment]
I don't see the two as entirely equivalent, because traits are not generic in the way that spells are. A spell name is a reference to a generic spell detailed in e.g. the PHB; a trait name is a label that helps identify a feature of a character, but which is fully described in the character statblock itself. You don't import traits into a character by name; you do import spells into a character by name.

That said, as I mentioned in my latest response to #261, I can be convinced that the parentheses have a place in the name as they qualify the actual capabilities of the spell/trait - "Spiritual Weapon (Trident)" is effectively different to "Spiritual Weapon" and you could imagine a character ending up with both from different sources. The asterisk for "cast before combat" on the other hand says nothing about the capabilities of the spell, merely a note on how the character uses it.
