### ISSUE TITLE
Monsters do not import with Actions

### ISSUE THREAD

**Issue by mlenser** [symposion/roll20-shaped-scripts#277]
If the token actions are set to show individual actions they are not created when a monster is imported. After the import is complete I can do a "!shaped-abilities --actions" to create them, but it's be great if the script does this automatically based on the hook that triggers at the end of the import.

**Comment by symposion** [comment]
I believe this is effectively a duplicate of #159. What is the "hook" that triggers at the end of import? Is it properly at the end, after all dependent updates have fired, or is it just after the first set of attributes have been set from the import data supplied by the script? 

The real solution to this is obviously to apply the new API sheetworkers stuff, but that got stalled with me having to help Riley debug their performance issues. I need to try and find the time to follow up on that but it's quite a big job because I need to fully instrument the sheet for performance logging, which is hard because of all the overlapping sets of asynchronous updates :-(

**Comment by mlenser** [comment]
It is a duplicate, sorry!

I understand the delays in implementation as it's all in flux from roll20's side.
