### ISSUE TITLE
Monster import damage of Orc War Chief is messed up

### ISSUE THREAD

**Issue by mlenser** [symposion/roll20-shaped-scripts#287]
I'm unsure if it's just this monster, but the damage is importing as:
"Hit: 15 (1d12 + 4"
"Hit: 12 (1d6 + 4if used with two hands to make a melee attack."

Orc seems to work just fine, so it's perhaps the syntax of this guy.

**Comment by mlenser** [comment]
Related issue I'm trying to solve: https://bitbucket.org/mlenser/5eshaped/issues/82/import-of-orc-war-chief-doesnt-apply

**Comment by symposion** [comment]
Cool ok, will check this out later. I'd be a bit surprised if it's the script since I just pass everything through to you as a block of text under content_srd. I guess the fix will either need to be in the JSON or the sheetworkers, but I'll double check to make sure i'm not somehow mangling the action text during import somehow.

**Comment by mlenser** [comment]
I checked the json and it's fine. It's possible that the plus regex I have is the cause here now that I think of it.

**Comment by mlenser** [comment]
Issue is definitely in my regex
