### ISSUE TITLE
Newest version crashing API Sandbox

### ISSUE THREAD

**Issue by NeighbourJim** [symposion/roll20-shaped-scripts#341]
Getting this error when the script is enabled, while the API Sandbox is starting up.

``"initialize.sheetOpened"
"abilities.update"
"abilityChecks.updateInitiative"
"savingThrows.updateMacro"
"initialize.generateSkills"
"abilityChecks.updateMacro"
TypeError: Cannot read property 'attribs' of undefined
TypeError: Cannot read property 'attribs' of undefined
    at Worker.onmessage (/home/node/d20-api-server/api.js:2770:20)
    at ChildProcess.<anonymous> (/home/node/d20-api-server/node_modules/tiny-worker/lib/index.js:39:21)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at handleMessage (internal/child_process.js:695:10)
    at Pipe.channel.onread (internal/child_process.js:440:11)``

Using the latest version of the script, as well as the most recent update of the shaped sheet itself, which is [version 9.2.1 as of now ](https://github.com/mlenser/roll20-character-sheets/tree/master/5eShaped).

**Comment by Gozer-the-Gozerian** [comment]
Doing the same with version 9.2.2
Here's the API log:

TypeError: Cannot read property 'attribs' of undefined
TypeError: Cannot read property 'attribs' of undefined
    at Worker.onmessage (/home/node/d20-api-server/api.js:2770:20)
    at ChildProcess.<anonymous> (/home/node/d20-api-server/node_modules/tiny-worker/lib/index.js:39:21)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at handleMessage (internal/child_process.js:695:10)
    at Pipe.channel.onread (internal/child_process.js:440:11)
Restarting sandbox due to script changes...
Previous shutdown complete, starting up...
Spinning up new sandbox...
"Starting webworker script..."
"Loading 873 translation strings to worker..."
"5eShapedCompanion 1488086389647 DEBUG : Making parser for field {\"formatVersion\":\"1.0.0\",\"name\":\"monsters\",\"maxOccurs\":\"Infinity\",\"type\":\"orderedContent\",\"bare\":true,\"contentModel\":[{\"name\":\"coreInfo\",\"type\":\"orderedContent\",\"flatten\":true,\"contentModel\":[{\"name\":\"name\",\"type\":\"string\",\"bare\":\"true\"},{\"name\":\"size\",\"enumValues\":[\"Tiny\",\"Small\",\"Medium\",\"Large\",\"Huge\",\"Gargantuan\"],\"type\":\"enumType\",\"bare\":\"true\"},{\"name\":\"type\",\"type\":\"string\",\"bare\":\"true\",\"pattern\":\"^([\\\\w\\\\s\\\\(\\\\),-]+),\",\"matchGroup\":1},{\"name\":\"alignment\",\"type\":\"enumType\",\"enumValues\":[\"(?:lawful|neutral|chaotic) (?:good|neutral|evil)(?:\\\\s?\\\\(\\\\d+%\\\\))? or (?:lawful|neutral|chaotic) (?:good|neutral|evil)(?:\\\\s?\\\\(\\\\d+%\\\\))?\",\"lawful good\",\"lawful neutral\",\"lawful evil\",\"neutral good\",\"neutral evil\",\"neutral\",\"chaotic good\",\"chaotic neutral\",\"chaotic evil\",\"chaotic\",\"lawful\",\"good\",\"evil\",\"unaligned\",\"any alignment\",\"any good alignment\",\"any non-good alignment\",\"any evil alignment\",\"any non-evil alignment\",\"any lawful alignment\",\"any non-lawful alignment\",\"any chaotic alignment\",\"any non-chaotic alignment\",\"construct\"],\"bare\":true}]},{\"name\":\"attributes\",\"type\":\"unorderedContent\",\"flatten\":true,\"contentModel\":[{\"name\":\"AC\",\"parseToken\":\"armor class\",\"pattern\":\"\\\\d+\\\\s*(?:\\\\([^)]*\\\\))?\",\"type\":\"string\"},{\"name\":\"HP\",\"parseToken\":\"hit points\",\"type\":\"string\",\"pattern\":\"\\\\d+(?:\\\\s?\\\\(\\\\s?\\\\d+d\\\\d+(?:\\\\s?[-+]\\\\s?\\\\d+)?\\\\s?\\\\))?\"},{\"name\":\"speed\",\"minOccurs\":0,\"type\":\"string\"},{\"name\":\"strength\",\"parseToken\":\"str\",\"type\":\"ability\"},{\"name\":\"dexterity\",\"parseToken\":\"dex\",\"type\":\"ability\"},{\"name\":\"constitution\",\"parseToken\":\"con\",\"type\":\"ability\"},{\"name\":\"intelligence\",\"parseToken\":\"int\",\"type\":\"ability\"},{\"name\":\"wisdom\",\"parseToken\":\"wis\",\"type\":\"ability\"},{\"name\":\"charisma\",\"parseToken\":\"cha\",\"type\":\"ability\"},{\"name\":\"savingThrows\",\"minOccurs\":0,\"parseToken\":\"saving throws\",\"type\":\"string\",\"pattern\":\"(?:(?:^|,\\\\s*)(?:Str|Dex|Con|Int|Wis|Cha)\\\\s+[\\\\-\\\\+]\\\\d+)+\"},{\"name\":\"skills\",\"minOccurs\":0,\"type\":\"string\",\"pattern\":\"(?:(?:^|,\\\\s*)(?:Acrobatics|Animal Handling|Arcana|Athletics|Deception|History|Insight|Intimidation|Investigation|Medicine|Nature|Perception|Performance|Persuasion|Religion|Sleight of Hand|Stealth|Survival|Influence|Society)\\\\s+[\\\\-\\\\+]\\\\d+)+\"},{\"minOccurs\":0,\"type\":\"string\",\"name\":\"damageVulnerabilities\",\"parseToken\":\"damage vulnerabilities\"},{\"minOccurs\":0,\"type\":\"string\",\"name\":\"damageResistances\",\"parseToken\":\"damage resistances\"},{\"minOccurs\":0,\"type\":\"string\",\"name\":\"damageImmunities\",\"parseToken\":\"damage immunities\"},{\"minOccurs\":0,\"type\":\"string\",\"name\":\"conditionImmunities\",\"parseToken\":\"condition immunities\"},{\"name\":\"senses\",\"type\":\"string\",\"minOccurs\":0},{\"name\":\"passivePerception\",\"parseToken\":\",?\\\\s*passive Perception\",\"minOccurs\":0,\"type\":\"number\",\"skipOutput\":true},{\"name\":\"spells\",\"minOccurs\":0,\"type\":\"string\"},{\"name\":\"languages\",\"minOccurs\":0,\"type\":\"string\"}]},{\"name\":\"challenge\",\"type\":\"string\",\"pattern\":\"^\\\\s*(\\\\d+(?:\\\\s*\\\\/\\\\s*\\\\d)?)\\\\s*(?:\\\\(\\\\s*[\\\\d,]+\\\\s*XP\\\\s*\\\\)\\\\s*)?$\",\"matchGroup\":1},{\"name\":\"traitSection\",\"type\":\"orderedContent\",\"minOccurs\":0,\"maxOccurs\":1,\"flatten\":true,\"contentModel\":[{\"name\":\"traits\",\"type\":\"orderedContent\",\"minOccurs\":1,\"maxOccurs\":\"Infinity\",\"contentModel\":[{\"name\":\"name\",\"type\":\"string\",\"pattern\":\"(^|.*?[a-z0-9]\\\\.\\\\s?)((?:[A-Z0-9][\\\\w\\\\-']+[,:!]?|A)(?:\\\\s(?:[A-Z0-9][\\\\w\\\\-']+[,:!]?|of|to|in|the|with|and|or|a|by|for)+)*(?:\\\\s?\\\\((?!Recharge|\\\\d+)[^\\\\)]+\\\\))?)(\\\\s?\\\\([^\\\\)]+\\\\))?\\\\.(?!$)\",\"matchGroup\":2,\"forPreviousMatchGroup\":1,\"forNextMatchGroup\":3,\"bare\":true,\"caseSensitive\":true},{\"name\":\"recharge\",\"type\":\"string\",\"pattern\":\"^\\\\(([^\\\\)]+)\\\\)\",\"bare\":true,\"matchGroup\":1,\"minOccurs\":0},{\"name\":\"text\",\"bare\":true,\"type\":\"string\"}]}]},{\"name\":\"actionSection\",\"type\":\"orderedContent\",\"minOccurs\":0,\"maxOccurs\":1,\"flatten\":true,\"contentModel\":[{\"name\":\"actionHeader\",\"type\":\"heading\",\"bare\":true,\"pattern\":\"^Actions$\"},{\"name\":\"actions\",\"type\":\"orderedContent\",\"minOccurs\":1,\"maxOccurs\":\"Infinity\",\"contentModel\":[{\"name\":\"name\",\"type\":\"string\",\"pattern\":\"(^|.*?[a-z]\\\\.\\\\s?)((?:\\\\d+\\\\.\\\\s?)?(?:[A-Z][\\\\w\\\\-']+[,:!]?|A|\\\\+\\\\d)(?:\\\\s(?:[A-Z][\\\\w\\\\-']+[,:!]?|of|in|to|with|the|and|or|by|for|a|\\\\+\\\\d+|2hd)+)*(?:\\\\s?\\\\((?!Recharge|\\\\d+)[^\\\\)]+\\\\))?)(\\\\s?\\\\([^\\\\)]+\\\\))?\\\\.(?!$)\",\"matchGroup\":2,\"forPreviousMatchGroup\":1,\"forNextMatchGroup\":3,\"bare\":true,\"caseSensitive\":true},{\"name\":\"recharge\",\"type\":\"string\",\"bare\":true,\"pattern\":\"^\\\\(([^\\\\)]+)\\\\)\",\"matchGroup\":1,\"minOccurs\":0},{\"name\":\"text\",\"bare\":true,\"type\":\"string\"}]}]},{\"name\":\"reactionSection\",\"type\":\"orderedContent\",\"minOccurs\":0,\"maxOccurs\":1,\"flatten\":true,\"contentModel\":[{\"name\":\"reactionHeader\",\"type\":\"heading\",\"bare\":true,\"pattern\":\"^Reactions$\"},{\"name\":\"reactions\",\"type\":\"orderedContent\",\"minOccurs\":1,\"maxOccurs\":\"Infinity\",\"contentModel\":[{\"name\":\"name\",\"type\":\"string\",\"pattern\":\"(^|.*?[a-z]\\\\.\\\\s?)((?:[A-Z][\\\\w\\\\-']+[,:!]?|A)(?:\\\\s(?:[A-Z][\\\\w\\\\-']+[,:!]?|of|in|to|with|the|and|or|a)+)*(?:\\\\s?\\\\((?!Recharge|\\\\d+)[^\\\\)]+\\\\))?)(\\\\s?\\\\([^\\\\)]+\\\\))?\\\\.(?!$)\",\"matchGroup\":2,\"forPreviousMatchGroup\":1,\"forNextMatchGroup\":3,\"bare\":true,\"caseSensitive\":true},{\"name\":\"recharge\",\"type\":\"string\",\"bare\":true,\"pattern\":\"^\\\\(([^\\\\)]+)\\\\)\",\"matchGroup\":1,\"minOccurs\":0},{\"name\":\"text\",\"bare\":true,\"type\":\"string\"}]}]},{\"name\":\"legendaryActionSection\",\"type\":\"orderedContent\",\"minOccurs\":0,\"maxOccurs\":1,\"flatten\":true,\"contentModel\":[{\"name\":\"actionHeader\",\"type\":\"heading\",\"bare\":true,\"pattern\":\"^Legendary Actions$\"},{\"name\":\"legendaryPoints\",\"type\":\"number\",\"bare\":true,\"pattern\":\"^(?:The)?[ \\\\w-]+(?:can|may) take (\\\\d+) legendary action(?:s)?.*?start.*?turn[.]?\",\"matchGroup\":1},{\"name\":\"legendaryActions\",\"type\":\"orderedContent\",\"minOccurs\":1,\"maxOccurs\":\"Infinity\",\"contentModel\":[{\"name\":\"name\",\"type\":\"string\",\"bare\":true,\"pattern\":\"(^|.*?[a-z]\\\\.\\\\s?)((?:[A-Z][\\\\w\\\\-']+[,:!]?|A)(?:\\\\s(?:[A-Z][\\\\w\\\\-']+[,:!]?|of|with|to|the|and|or|a)+)*)(\\\\s?\\\\([^\\\\)]+\\\\))?\\\\.(?!$)\",\"matchGroup\":2,\"forPreviousMatchGroup\":1,\"forNextMatchGroup\":3,\"caseSensitive\":true},{\"name\":\"cost\",\"type\":\"number\",\"bare\":true,\"pattern\":\"^\\\\s*\\\\(\\\\s*(?:costs )?(\\\\d+) actions\\\\s*\\\\)\",\"matchGroup\":1,\"minOccurs\":0},{\"name\":\"text\",\"bare\":true,\"type\":\"string\"}]}]},{\"name\":\"lairActionSection\",\"type\":\"orderedContent\",\"minOccurs\":0,\"maxOccurs\":1,\"flatten\":true,\"contentModel\":[{\"name\":\"actionHeader\",\"type\":\"heading\",\"pattern\":\"^Lair Actions$\"},{\"name\":\"lairActionBlurb\",\"type\":\"heading\",\"pattern\":\"^On initiative count 20[^:]+:*$\"},{\"name\":\"lairActions\",\"type\":\"string\",\"bare\":true,\"pattern\":\"^(?:\\\\*|•)\\\\s?((?:.|\\n)*)\",\"matchGroup\":1,\"minOccurs\":1,\"maxOccurs\":\"Infinity\"}]},{\"name\":\"regionalEffectsSection\",\"type\":\"orderedContent\",\"minOccurs\":0,\"maxOccurs\":1,\"flatten\":true,\"contentModel\":[{\"name\":\"actionHeader\",\"type\":\"heading\",\"pattern\":\"^Regional Effects$\"},{\"name\":\"regionalBlurb\",\"type\":\"heading\",\"minOccurs\":0,\"pattern\":\"^The region (?:containing|around|surrounding)[^:]+:$\"},{\"name\":\"regionalEffects\",\"type\":\"string\",\"minOccurs\":1,\"maxOccurs\":\"Infinity\",\"bare\":true,\"pattern\":\"^(?:\\\\*|•)\\\\s?((?:.|\\n)*)\",\"matchGroup\":1},{\"name\":\"regionalEffectsFade\",\"type\":\"string\",\"bare\":true,\"pattern\":\"^(?:if|when)[\\\\w\\\\s-]+(?:dies|is destroyed).*$\"}]}]}"
"5eShapedCompanion 1488086394376 INFO : -=> ShapedScripts v6.2.1 <=-"
"5eShapedCompanion 1488086394377 INFO : Checking config for upgrade, starting state: {\"version\":3.7,\"config\":{\"genderPronouns\":[{\"matchPattern\":\"^f$|female|girl|woman|feminine\",\"nominative\":\"she\",\"accusative\":\"her\",\"possessive\":\"her\",\"reflexive\":\"herself\"},{\"matchPattern\":\"^m$|male|boy|man|masculine\",\"nominative\":\"he\",\"accusative\":\"him\",\"possessive\":\"his\",\"reflexive\":\"himself\"},{\"matchPattern\":\"^n$|neuter|none|construct|thing|object\",\"nominative\":\"it\",\"accusative\":\"it\",\"possessive\":\"its\",\"reflexive\":\"itself\"}],\"logLevel\":\"INFO\",\"tokenSettings\":{\"number\":false,\"bar1\":{\"attribute\":\"HP\",\"max\":true,\"link\":false,\"showPlayers\":false},\"bar2\":{\"attribute\":\"AC\",\"max\":false,\"link\":true,\"showPlayers\":false},\"bar3\":{\"attribute\":\"\",\"max\":false,\"link\":false,\"showPlayers\":false},\"aura1\":{\"radius\":\"\",\"color\":\"#FFFF99\",\"square\":false},\"aura2\":{\"radius\":\"\",\"color\":\"#59e594\",\"square\":false},\"light\":{\"radius\":\"\",\"dimRadius\":\"\",\"otherPlayers\":false,\"hasSight\":true,\"angle\":360,\"losAngle\":360,\"multiplier\":1},\"showName\":true,\"showNameToPlayers\":false,\"showAura1ToPlayers\":true,\"showAura2ToPlayers\":true,\"monsterTokenName\":\"\"},\"newCharSettings\":{\"sheetOutput\":\"***default***\",\"deathSaveOutput\":\"***default***\",\"initiativeOutput\":\"***default***\",\"showNameOnRollTemplate\":\"{{show_character_name=1}}\",\"rollOptions\":\"***default***\",\"initiativeRoll\":\"\",\"initiativeToTracker\":0,\"breakInitiativeTies\":false,\"showTargetAC\":false,\"showTargetName\":false,\"autoAmmo\":true,\"autoRevertAdvantage\":true,\"houserules\":{\"mediumArmorMaxDex\":0,\"saves\":{\"useCustomSaves\":false,\"useAverageOfAbilities\":false,\"fortitude\":{\"fortitudeStrength\":false,\"fortitudeDexterity\":false,\"fortitudeConstitution\":false,\"fortitudeIntelligence\":false,\"fortitudeWisdom\":false,\"fortitudeCharisma\":false},\"reflex\":{\"reflexStrength\":false,\"reflexDexterity\":false,\"reflexConstitution\":false,\"reflexIntelligence\":false,\"reflexWisdom\":false,\"reflexCharisma\":false},\"will\":{\"willStrength\":false,\"willDexterity\":false,\"willConstitution\":false,\"willIntelligence\":false,\"willWisdom\":false,\"willCharisma\":false},\"savingThrowsHalfProf\":false},\"baseDC\":\"***default***\",\"expertiseAsAdvantage\":false,\"inspirationMultiple\":true,\"criticalDamageHouserule\":\"***default***\",\"proficiencyDice\":false,\"psionics\":false,\"customClasses\":false,\"honorToggle\":false,\"sanityToggle\":false},\"tab\":\"***default***\",\"tokenActions\":{\"initiative\":false,\"abilityChecks\":null,\"advantageTracker\":null,\"savingThrows\":null,\"attacks\":null,\"statblock\":false,\"traits\":null,\"actions\":null,\"reactions\":null,\"legendaryActions\":null,\"lairActions\":null,\"regionalEffects\":null,\"rests\":false,\"spells\":false,\"showRecharges\":false,\"racialFeatures\":null,\"classFeatures\":null,\"feats\":null},\"textSizes\":{\"spellsTextSize\":\"***default***\",\"abilityChecksTextSize\":\"***default***\",\"savingThrowsTextSize\":\"***default***\"},\"hide\":{\"hideAttack\":\"***default***\",\"hideDamage\":\"***default***\",\"hideAbilityChecks\":\"***default***\",\"hideSavingThrows\":\"***default***\",\"hideSavingThrowDC\":\"***default***\",\"hideSpellContent\":\"***default***\",\"hideSavingThrowFailure\":\"***default***\",\"hideSavingThrowSuccess\":\"***default***\",\"hideRecharge\":\"***default***\",\"hideFreetext\":\"***default***\",\"hideCost\":\"***default***\"},\"applyToAll\":true,\"hitDiceOutput\":\"***default***\",\"display\":{\"showPassiveSkills\":false,\"showWeight\":\"***default***\",\"showEmote\":false,\"showFreetext\":false,\"showFreeform\":false,\"showDiceModifiers\":false,\"showCritRange\":false,\"extraOnACrit\":false,\"showRests\":\"***default***\"},\"measurementSystems\":{\"distanceSystem\":\"***default***\",\"weightSystem\":\"***default***\",\"encumbranceMultiplier\":1},\"automaticHigherLevelQueries\":\"***default***\"},\"advTrackerSettings\":{\"showMarkers\":true,\"ignoreNpcs\":false,\"advantageMarker\":\"green\",\"disadvantageMarker\":\"red\",\"output\":\"silent\"},\"sheetEnhancements\":{\"rollHPOnDrop\":true,\"autoHD\":true,\"autoSpellSlots\":true,\"autoTraits\":true},\"defaultGenderIndex\":2,\"variants\":{\"rests\":{\"longNoHpFullHd\":false}}}}"
"ERROR: You cannot set the imgsrc or avatar of an object unless you use an image that is in your Roll20 Library. See the API documentation for more info."
"ERROR: You cannot set the imgsrc or avatar of an object unless you use an image that is in your Roll20 Library. See the API documentation for more info."
"5eShapedCompanion 1488086394450 INFO : Summary of adding CurseOfStrahd entity group to the lookup: {\"errors\":0,\"entityGroupName\":{},\"monsters\":{\"withErrors\":0,\"skipped\":0,\"deleted\":0,\"patched\":0,\"added\":20}}"
"5eShapedCompanion 1488086394461 INFO : Summary of adding HoardOfTheDragonQueen entity group to the lookup: {\"errors\":0,\"entityGroupName\":{},\"monsters\":{\"withErrors\":0,\"skipped\":0,\"deleted\":0,\"patched\":0,\"added\":15}}"
"5eShapedCompanion 1488086394464 INFO : Summary of adding LostMineOfPhandelver entity group to the lookup: {\"errors\":0,\"entityGroupName\":{},\"monsters\":{\"withErrors\":0,\"skipped\":0,\"deleted\":0,\"patched\":0,\"added\":5}}"
"5eShapedCompanion 1488086394686 INFO : Summary of adding MonsterManual entity group to the lookup: {\"errors\":0,\"entityGroupName\":{},\"monsters\":{\"withErrors\":0,\"skipped\":0,\"deleted\":0,\"patched\":0,\"added\":454}}"
"5eShapedCompanion 1488086394704 INFO : Summary of adding OutOfTheAbyss entity group to the lookup: {\"errors\":0,\"entityGroupName\":{},\"monsters\":{\"withErrors\":0,\"skipped\":0,\"deleted\":0,\"patched\":0,\"added\":35}}"
"5eShapedCompanion 1488086394725 INFO : Summary of adding PrincesOfTheApocalypse entity group to the lookup: {\"errors\":0,\"entityGroupName\":{},\"monsters\":{\"withErrors\":0,\"skipped\":0,\"deleted\":0,\"patched\":0,\"added\":42}}"
"5eShapedCompanion 1488086394729 INFO : Summary of adding TheRiseOfTiamat entity group to the lookup: {\"errors\":0,\"entityGroupName\":{},\"monsters\":{\"withErrors\":0,\"skipped\":0,\"deleted\":0,\"patched\":0,\"added\":7}}"
"5eShapedCompanion 1488086394932 INFO : Summary of adding TomeOfBeasts entity group to the lookup: {\"errors\":0,\"entityGroupName\":{},\"monsters\":{\"withErrors\":0,\"skipped\":0,\"deleted\":0,\"patched\":0,\"added\":406}}"
"5eShapedCompanion 1488086394948 INFO : Summary of adding spellData entity group to the lookup: {\"errors\":0,\"entityGroupName\":{},\"spells\":{\"withErrors\":0,\"skipped\":0,\"deleted\":0,\"patched\":0,\"added\":408}}"
"initialize.sheetOpened"
"abilities.update"
"abilityChecks.updateInitiative"
"savingThrows.updateMacro"
"initialize.generateSkills"
"abilityChecks.updateMacro"
"abilityChecks.updateSkill"
TypeError: Cannot read property 'attribs' of undefined
TypeError: Cannot read property 'attribs' of undefined
    at Worker.onmessage (/home/node/d20-api-server/api.js:2770:20)
    at ChildProcess.<anonymous> (/home/node/d20-api-server/node_modules/tiny-worker/lib/index.js:39:21)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at handleMessage (internal/child_process.js:695:10)
    at Pipe.channel.onread (internal/child_process.js:440:11)

Looks like it's the same thing

**Comment by symposion** [comment]
Ok, so I'm hoping 6.3.0 will fix this.
