### ISSUE TITLE
Request: Use Targets Name and Targets AC options only when is an ATTACK

### ISSUE THREAD

**Issue by Jimwaters** [symposion/roll20-shaped-scripts#369]
Certain items that are logically attacks are set up with the Attack tickbox not set.  This appears to be for attacks, such as Dragon Breath, and Frightful Presence, which do not target AC.   I hope this is the case consistently...

Technically 5e defines the attack option in purely physical terms, so the examples above and all spells are not Attack Actions.  They exist in the Actions part of the sheet, which seems to be called Attack section in documentation.

My suggestion is to extend this logic to say that if the Attack option is not set for an action then the use Targets Name and Targets AC options is not active.

This would, perhaps, refine the meaning of the Attack tickbox for an action - to be _an attack versus AC_ and change script to match.  This would work well for Booming Blade, Sneak Attack, and all attacks that do not target AC.  

Downside is that any Action that does not have Attack ticked, but targets AC would have to be manually changed, and vice-versa.  As this is a simple tick box I suggest a GM can change these as they come up in a game, if not detected before.

**Comment by symposion** [comment]
Hi,
So I'm going to close this as WontFix because this is not to do with the script. The behaviour here is entirely determined by the sheet. The only thing that the script does is to let you default the state of the two tickboxes on the settings page for new/imported characters - it doesn't actually have a hand  in what happens thereafter.

If you want this functionality to change, you need to raise on issue on Kryx's tracker for the sheet. However, before you do that, you need to consider some things:

1. In 5e, an attack is a specific thing. It's a D20 roll to which you add an ability modifier, and usually your proficiency bonus, that is contested by a target's AC. If it isn't a D20 roll vs AC, it isn't an attack. If it's an attack, it's always contested by AC. So if something has the attack tickbox checked, and you've chosen to show target AC on attacks, it's going to show it, and that means it's going to prompt for a target. As far as I'm aware, an attack roll in 5e is always against a single target, so this makes sense. If you're asking Kryx to change the meaning of "attack", you're wasting your time: he's a stickler for correctness in terminology vs the rules and he won't do it.
2. The option to show name is "Show name on attacks and saves". Your suggestion amounts to changing this to "show name on attacks" and redefining what an attack means to fit the behaviour you're looking for. I've explained why this won't happen above. But in fact, I think you're asking for the wrong thing. There are plenty of effects that require saves where it makes sense to select a single target and then display that target in the roll template output. The key thing here is not whether it's an attack or not; it's what the target is. If there's a single target, it makes sense to prompt for it; if it's an AOE, not so much (I got part way through writing a script that let you do proper AOE targeting but I no longer have time to finish it :-( ) I suggested to Kryx a long time ago that the "show name" thing should be suppressed for AOEs, but at the time it wasn't technically possible. With sheetworkers it might now be feasible, and he might consider doing it. You would be better off requesting this than what you've written above: it's more formally correct according to the rules and I think it will achieve what you need.

**Comment by Jimwaters** [comment]
Thanks for the answer.  I had missed that it was attacks AND SAVES - hence my "confusion".

Attack has so many meanings, which is down to WotC.  

Anyway sorry to take up even more of your time....
