### ISSUE TITLE
Automatically roll damage

### ISSUE THREAD

**Issue by mlenser** [symposion/roll20-shaped-scripts#395]
Please add options to **!shaped-config** for turning off automatic roll of damage.

**automatically_roll_damage_for_attacks** and **automatically_roll_damage_for_saving_throws**. Both default to 1 and can be set to 0 to manually roll damage.

These belong under roll template settings if you have a similar structure to mine.

**Comment by symposion** [comment]
Ok, I've added this now. There's a development version with it that's installed on your test campaign. I've done that because I've also added a class to the !shaped-config menu table element ('userscript-shaped-config') and I was hoping that when you were looking at styling the streaming messages you could also have a look at the shaped-config styling. It got a broken by the move to being inside the roll template and it doesn't look quite right now.

I've left the style attributes on the individual elements in the layout so that you can see how it works at the moment. Let me know when you want them removed.
