### ISSUE TITLE
Handle Rests running on the sheet

### ISSUE THREAD

**Issue by mlenser** [symposion/roll20-shaped-scripts#398]
With the move of rests to the sheet we'll need to change how the API references them.

For rests they can toggle a field and the sheet should pick up the field and recharge the appropriate fields.

They can follow the format of `change:short_rest`, `change:long_rest`, `change:recharge_turn`, etc. Let me know how you want the recharge 5-6 worded. Probably `change:recharge_5_6`

Once the sheetworkers execute then we'll need to grab a field from the sheet that contains information on what was recharged, but that can be step 2.

**Comment by symposion** [comment]
I'm not convinced that it makes sense to handle recharge_5_6 in the sheet, at least not in any substantial way. Without the ability to roll dice in sheetworkers, there's no way that this can work in any useful way for non-pro users. In fact, I think this actually work the other way round. When you do a turn recharge because the user clicks "turn recharge", I will listen to the pseudo-button attribute; I will look for traits that need a recharge_5_6 style recharge, roll the die, and then set the uses as appropriate. Where the recharge is launched from a token action I will just do it directly without watching the attribute. Make sense?
