### ISSUE TITLE
Token actions: Query-mode Saving throws and Ability checks broken

### ISSUE THREAD

**Issue by liquidox** [symposion/roll20-shaped-scripts#401]
Saving throws, on button press, now shows:
Strength +0,{{title=Strength Saving throw&#125;&#125; {{roll1=[[d20 + 0[str] + {{d20=1

Ability checks shows:
Strength +0,{{title=Strength&#125;&#125; {{roll1=[[d20 + {{d20=1

This was tested on a newly made PC. Same issue appears on MM/VG imports.

It certainly has worked at some point last week, likely with an older version of the companion script.

**Comment by symposion** [comment]
Hey, 
This is a sheet bug. You can tell that because if you create a character manually and click the button for the 'ability checks query' from the settings page of the sheet, it still happens, even if the companion script isn't even installed. You need to report it over here: https://bitbucket.org/mlenser/5eshaped/issues?status=new&status=open
