### ISSUE TITLE
Generically named spells in the SRD are not replaced by their full Player's Handbook names.

### ISSUE THREAD

**Issue by mlenser** [symposion/roll20-shaped-scripts#418]
Example: Acid Arrow -> Melf's Acid Arrow

I use the syntax to rename the spell:
`
{
  "name": "Acid Arrow",
  "newName": "Melf's Acid Arrow"
}
`
And include the new name on the class' list, but I still see "Acid Arrow" in the list and "Melf's Acid Arrow" is not on the list.

**Comment by symposion** [comment]
This  works fine for me. I suspect that the problem is that you've omitted "patch":true from your patch file, in which case it will try to merge the data rather than patching the existing info.

**Comment by mlenser** [comment]
Seems to be working as intended with patch: true, but that seems unnecessary to include. When you would not want patch to be true?

**Comment by symposion** [comment]
The behaviour is subtly different. With patch:true, values in the patch file are always used in preference to the original values when present. With patch:false, the original values are used, but you can splice new entries into array values on the entity rather than completely replacing them.

Probably this does need to be rationalised into a more expressive way of handling edits to array values, since this stuff just kind of evolved, but I don't see it as a major priority right now since we're basically the only two people using the system!
