### ISSUE TITLE
Casting class features does not deduct from available spell slots.

### ISSUE THREAD

**Issue by sirren58** [symposion/roll20-shaped-scripts#420]
When I test and cast regular spells from the PC's sheet it deducts properly, but when I cast Paladin's Divine Smite from the class features section for example it does not deduct the appropriate spell slot.
If I remember right it used to work in 8.0.0.

**Comment by symposion** [comment]
Kryx and I have been looking at this and we're not sure how it ever worked. It turns out to be quite hard to do properly given they way divine smite works in the sheet, since the sheet makes no distinction between using a 5th vs a 4th level slot, since they have the same effect, but obviously the script would need the correct information to decrement slots properly.  I'm still talking to Kryx about possible workarounds, but I think for the moment you may be stuck doing this manually.

**Comment by sirren58** [comment]
I found a solution for myself. The reason I needed this to work is because
I was referencing Divine Smite class feature in my player's Paladin macros.

So instead I create a level 1 spell that mimics Divine Smite class feature
and am referencing that spell now.

May be you can do something similar with the script, making it think that
the Divine Smite class feature is actually a Spell.
Because for all intents and purposes it is.

Here are some images:

[image: Inline image 1]

[image: Inline image 2]

**Comment by symposion** [comment]
Well, that's actually pretty similar to the way the Divine Smite class feature works. The problem with your version is that it doesn't impose a cap on the damage. If a Paladin uses a 5th level slot, he shouldn't get 6d8 damage. Maintaining this restriction is what is making the implementation of the feature hard.
