### ISSUE TITLE
Monster List shows after monster import complete

### ISSUE THREAD

**Issue by mlenser** [symposion/roll20-shaped-scripts#456]
Is there a reason to return the monsters list after importing a monster?

workflow:
1. Select a token   
2. find monster on list from !shaped-monster
3. click monster on the list in chat
4. Monster is imported
5. Monst list shows again after the import log and before hp

**Comment by symposion** [comment]
It works this way because it works the same way as the spells lister (it's the same code).  Personally I quite often drop a whole load of tokens on the tabletop and then import them one after another, in which case the current behaviour is actually nice - I don't have to repeat the !shaped-monsters command each time. But I grant you that "losing" the import results and having the HP come afterwards is a problem. What I really want is a notification window for the results that can be dismissed, leaving the list behind. I guess I could try and simulate that using a z-index overlay...

**Comment by mlenser** [comment]
It's a bit presumptuous to presume that there will be multiple monster imports. My workflow is quite different in that I typically do 1 monster and then am done. I'm not sure how to capture this difference, but what you're considering a feature I'd consider a bug.

The desire for a notification window is too much for roll20 I expect. In the normal world a small notification would appear for a few seconds and then disappear. I'm not sure we can replicate that behavior on roll20.

**Comment by symposion** [comment]
Sorry, I wasn't doing any presuming! The behaviour is there just because it was coded that way for spells and it shares the same code. It never occurred to me to change it because for me it's generally desirable, but I can see that it won't be for everyone/every case. I'll have a play and see what I can do. I guess maybe in the worst case I'll just have to put in an option somewhere, but I'd rather have a UI that works for all cases if possible.

**Comment by mlenser** [comment]
Perhaps "Import another monster/spell" button at the bottom of the success notification?
