### ISSUE TITLE
Support Rest buttons from the sheet

### ISSUE THREAD

**Issue by Brunhine** [symposion/roll20-shaped-scripts#77]
Kryx is adding a short rest and long rest button to the sheet.

Provide support for those

**Comment by symposion** [comment]
Wow, this looks cool. However, I think there's a slight problem with the implementation - Kryx has implemented these buttons as a toggle. What this means is that the first button push changes the value from 0 to 'on', and the next one from 'on' to 0. You are checking for 'on' so you are only responding to the button pushes 50% of the time!

For the time being I will push a fix that checks that the current value !== the previous value, but it might be worth considering asking Kryx to change this into a Roll button that issues an API command (if that's possible) rather than an attribute toggle. It would save him a couple of attributes in the sheet, it would be cleaner and there would be less risk on unexpected side-effects from other modifications to the attribute - e.g. people manually editing or other scripts doing stuff.

**Comment by Brunhine** [comment]
Actually, the script set the value of the rest attributes back to 0 when it completed.

**Comment by Brunhine** [comment]
So I think this means that your fix will cause the rests to fire in an infinite loop.
